### ISSUE TITLE
1.2.2 Fresh install fails to launch

### ISSUE THREAD

**Issue by BGraco** [RomanBelkov/DiskImager#1]
If you launch 1.2.1 the issues is resolved and 1.2.2 can launch without errors.

Very repeatable on a windows 7 virtual machine.

I can seem to post an image of the error message, but it is unhappy  with the change language/read registry code.

**Comment by BGraco** [comment]
I cant seem to attach the image. If you give me an email I will send a capture.

**Comment by RomanBelkov** [comment]
Hi! 

You can send me an e-mail: romanbelkov@gmail.com

Please describe an issue in details, so I'd be able to deal with it ASAP

**Comment by RomanBelkov** [comment]
Please check if new version 1.2.2-fix is launching
