### ISSUE TITLE
Can not write at all

### ISSUE THREAD

**Issue by ROdoka** [RomanBelkov/DiskImager#5]
Hey, nice piece of software!
I need to write images on several SDcards at once using Win7 x64.
Instead of opening many win32diskimage instances, I was looking for an altered version that needs only one instance and so I found your program.

But I can't write to any SD card at all!
After selecting one or many drives and clicking on the "restore ..." button, selected an .img-File I get a message saying "Write Error" "Problem writing to disk. Is it write-protected?"
After that I get "All done!" "All drives are ready"

But none of the SDcards are protected or done!

**Comment by RomanBelkov** [comment]
OK, this is very strange so help me out a bit:
1. What version of DiskImager are you using?
2. Can you write to a drive using Win32DiskImager?
3. I know, it may seem dumb, but try un-plugging the drive, plug it back in and try writing. Currently I have a trouble that even in case of failure drives are un-mounted from Windows, therefore making them unable to be used for restoring.
4. If none of the above helps, then write me here once again and I'll send you a debug version to know what's up. It may take some time, because currently I barely have time to breathe, but I'll be as helpful as I can.

Thanks!

**Comment by ROdoka** [comment]
Hello Roman, thanks for replying :)
1. I used the newest version and also tried older versions, all of them have this problem here.
2. I used win32diskimager 1.3 for Odroid before, also v0.9.5 (if I remember correctly), without any problems
3. I tried that, too, with different card reader sticks, using formatted SD cards and also with cards with a RAW partition
   I just tried something else: before I connected the card reader using an USB hub, this time I plugged it directly into a USB port, same problem
4. done :) and no hurries! As long as it helps to fix some bugs or to improve DiskImager, it's alright :)

Best regards!

**Comment by tociek** [comment]
In my case this error was caused by one of two reasons :
1) shitty sd card reader
2) size of the image was too big for sd card
If you succeeded with using the same hardware and win32DiskImager then none of the above would be a problem though...

**Comment by ROdoka** [comment]
I just tried the PC's built-in card reader, same problem
I also tried different image sizes, they all can be written with win32DiskImager that I've found in the Odroid forum
I've just installed the original 0.9.5 version again and it works ...

**Comment by markus07** [comment]
I got the same problem. Disk Imager v1.4.1.31470. I use 7 ports USB 3.0 hub with power adapter and 3x USB 3.0 card readers + 4x USB 2.0 card readers. So total is 7.

When I try to restore drives from backup got the same error on random card readers "Write Error" "Problem writing to disk. Is it write-protected?"

Sometimes it works fine with 3-4 drives, others got write error.

**Comment by markus07** [comment]
Just to let you know, I used portable version and it works like a charm !
![di](https://cloud.githubusercontent.com/assets/5395911/15379813/b46da5fa-1dab-11e6-8f5e-167609e6e899.JPG)

**Comment by ROdoka** [comment]
I also use the portable version (well also tried the installer)
I just got a new fast card writer, but the problem is the same as before

**Comment by RomanBelkov** [comment]
@ROdoka 
Also a quick idea on what can possibly go wrong: Have you tried running the program with administrative privileges explicitly? I mean "Right Click -> Run as Admin"

**Comment by ROdoka** [comment]
yes, that doesn't change anything :)

I just tried the portable version on a WinXP machine with user (non-admin) account and it won't start (seems like it has no access to some registry keys there)

**Comment by RomanBelkov** [comment]
@ROdoka 
Yes, it does some operations with registry to remember a couple of settings.
Also, can you please try and make a screenshot of main program window on windows 7 after program has failed or write down to me what does the program say in the very bottom line (usually at the start this line says "Initialized. Licensed under GPLv3")

**Comment by ROdoka** [comment]
![di_problem](https://cloud.githubusercontent.com/assets/18678990/15389872/49b55394-1db9-11e6-8cce-3e1e4ec0d0ae.png)

does this help you?

**Comment by RomanBelkov** [comment]
@ROdoka Yes, this helps a lot. I'll make the version that would be stuffed with logging all over the troublesome part ASAP (probably in the next 48 hours)

**Comment by ROdoka** [comment]
@RomanBelkov many thanks :)

**Comment by ROdoka** [comment]
hm :)

**Comment by RomanBelkov** [comment]
I am so sorry, I had a lot of exams and was completely unable to do something on the matter. I am going to have a rest for some time and get back to the issue.

**Comment by RomanBelkov** [comment]
Hi guys, check this out
https://github.com/RomanBelkov/DiskImager/releases/tag/attempt-1
If things are not fixed, please attach the file that is located in installation folder\Logs

**Comment by ROdoka** [comment]
Hello Roman,
this new version works without any problems :)
many thanks for fixing this!

**Comment by RomanBelkov** [comment]
OK, fine. Then I will apply the necessary changes and produce a new (kind of) stable release. After that the issue could be closed, I believe.

Thank you for cooperation and tons of patience :smiley:

**Comment by ROdoka** [comment]
I didn't close this yet, so I'll do it now :)
